// smart words
var smartWords = [
[["accolade"], ["a tangible symbol signifying approval or distinction"]],
[["acrimony"], ["bitterness"]],
[["angst"], ["an acute but unspecific feeling of anxiety"]],
[["anomaly"], ["abnormality"]],
[["antidote"], ["a remedy that stops or controls the effects of a poison"]],
[["avant-garde"],[ "Ahead of the times, especially in the arts"]],
[["baroque"], ["having elaborate symmetrical ornamentation"]],
[["bona"], ["fide not counterfeit or copied"]],
[["bourgeois"], ["a member of the middle class; belonging to the middle class"]],
[["boondoggle"], ["work of little or no value done merely to look busy"]],
[["bravado"], ["a swaggering show of courage"]],
[["brogue"], ["a thick and heavy shoe; a strong dialectal accent"]],
[["brusque"], ["rudely abrupt"]],
[["byzantine"], ["highly involved or intricate"]],
[["cacophony"], ["a loud harsh or strident noise"]],
[["camaraderie"], ["trust among friends"]],
[["capricious"], ["impulsive and unpredictable"]],
[["carte"], ["blanche authority with no bounds"]],
[["Catch-22"],["a lose lose situation"]],
[["caustic"], ["sarcastic"]],
[["charisma"], ["charm"]],
[["cloying"], ["excessively sweet or sentimental"]],
[["déjà"], ["vu the experience of thinking that a new situation had occurred before"]],
[["dichotomy"], ["a division into two parts"]],
[["dilettante"], ["showing frivolous or superficial interest"]],
[["élan"], ["enthusiastic vigor or liveliness"]],
[["disheveled"], ["in disarray"]],
[["ennui"], ["boredom"]],
[["epitome"], ["a typical example"]],
[["equanimity"], ["steadiness of mind under stress"]],
[["equivocate"], ["to be deliberately ambiguous or unclear in order to mislead or withhold information"]],
[["esoteric"], ["intended for or understood by only a small group"]],
[["euphemism"], ["an inoffensive expression that is substituted for one that is considered offensive"]],
[["fait"], ["accompli an irreversible accomplishment"]],
[["fastidious"], ["difficult to please"]],
[["faux"], ["pas a social blunder"]],
[["fiasco"], ["a complete failure"]],
[["finagle"], ["to trick, swindle or cheat"]],
[["Freudian"], ["slip a verbal mistake that is thought to reveal an unconscious belief, thought, or emotion"]],
[["glib"], ["artfully persuasive in speech"]],
[["gregarious"], ["sociable"]],
[["harbinger"], ["an omen or sign; forerunner"]],
[["hedonist"], ["a pleasure seeker"]],
[["heresy"], ["a belief that rejects the orthodox tenets of a religion"]],
[["idiosyncratic"], ["peculiar to the individual"]],
[["idyllic"], ["charming in a rustic way; suggestive of an idyll"]],
[["indelicate"], ["lacking propriety and good taste in manners and conduct"]],
[["infinitesimal"], ["immeasurably small"]],
[["insidious"], ["treacherous"]],
[["junket"], ["a trip taken by an official often times for pleasure at public expense"]],
[["kitsch"], ["art in pretentious bad taste"]],
[["litany"], ["any long, repetitive, or dull recital"]],
[["lurid"], ["ghastly pale"]],
[["Machiavellian"], ["unprincipled and crafty"]],
[["malaise"], ["physical discomfort (as mild sickness or depression)"]],
[["malinger"], ["to evade responsibility by pretending to be ill"]],
[["mantra"], ["a commonly repeated word or phrase"]],
[["maudlin"], ["overemotional"]],
[["mercenary"], ["a professional soldier hired by a foreign army; profit oriented"]],
[["minimalist"], ["a person who practices arts in less detailed ways"]],
[["misnomer"], ["an incorrect or unsuitable name"]],
[["narcissist"], ["someone in love with themselves"]],
[["nirvana"], ["any place of complete bliss and delight and peace"]],
[["non"], ["sequitur something that does not logically follow"]],
[["nouveau"], ["riche newly rich"]],
[["oblivion"], ["total forgetfulness"]],
[["ogle"], ["look at with amorous intentions"]],
[["ostentatious"], ["showy"]],
[["ostracize"], ["to exclude from a group; banish; exile"]],
[["panacea"], ["cure-all; remedy for all diseases"]],
[["paradox"], ["a contradiction or dilemma"]],
[["peevish"], ["easily irritated or annoyed"]],
[["perfunctory"], ["hasty and without attention to detail"]],
[["philistine"], ["a person who is uninterested in intellectual pursuits"]],
[["precocious"], ["appearing or developing early"]],
[["propriety"], ["correct or appropriate behavior"]],
[["quid"], ["pro quo this for that"]],
[["quintessential"], ["perfect example"]],
[["red"], ["herring any diversion intended to distract attention from the main issue"]],
[["revel"], ["to take delight in"]],
[["rhetoric"], ["effective writing or speaking"]],
[["scintillating"], ["brilliantly clever"]],
[["spartan"], ["marked by simplicity and lack of luxury"]],
[["stigma"], ["a symbol of disgrace or infamy"]],
[["stoic"], ["unaffected by pleasure or pain"]],
[["suave"], ["having a sophisticated charm"]],
[["Svengali"], ["A person who exercises excessive control or influence over another person"]],
[["sycophant"], ["a self-serving flatterer, a brownnoser"]],
[["teetotaler"], ["one who does not drink alcohol"]],
[["tête-à]-tête"], ["a private conversation between two people"]],
[["tirade"], ["a long, angry speech, usually very critical"]],
[["tryst"], ["a secret meeting of lovers; rendezvous"]],
[["ubiquitous"], ["being present everywhere at once"]],
[["unrequited"], ["not returned in kind"]],
[["untenable"], ["indefensible"]],
[["vicarious"], ["done or felt for, or on behalf of, another"]],
[["vile"], ["morally reprehensible"]],
[["waft"], ["be driven or carried along, as by the air"]],
[["white"], ["elephant a possession that costs more to keep than its worth"]],
[["zealous"], ["enthusiastic; fervent; fanatical"]]]